DECLARE @NOMBRE VARCHAR (30)
DECLARE @GrupoID VARCHAR(20)
DECLARE @TITULO VARCHAR (30)
DECLARE @CANCION VARCHAR(30)

DECLARE CURSOR_GRUPO CURSOR FOR SELECT Nombre, Grupo_id FROM grupos
	OPEN CURSOR_GRUPO
	FETCH NEXT FROM CURSOR_GRUPO INTO @NOMBRE, @grupoID
	WHILE (@@FETCH_STATUS = 0)
    BEGIN
		PRINT 'GRUPO: ' + @NOMBRE
		DECLARE CURSOR_DISCOS CURSOR FOR	SELECT discos.Titulo
											FROM discos ,grupos
											WHERE grupos.Nombre = @NOMBRE
											AND discos.Grupo_id = Grupos.Grupo_id
			OPEN CURSOR_DISCOS
			FETCH NEXT FROM CURSOR_DISCOS INTO @titulo
			WHILE (@@FETCH_STATUS = 0)
			BEGIN
				PRINT '         DISCOS: ' + @TITULO
				DECLARE CURSOR_CANCIONES CURSOR 
				FOR SELECT canciones.Titulo
					FROM  discos ,disco_cancion,canciones
					WHERE discos.Titulo = @TITULO
					AND discos.Disco_id=disco_cancion.Disco_id
					AND disco_cancion.Cancion_id=canciones.Cancion_id
				OPEN CURSOR_CANCIONES
				FETCH NEXT FROM CURSOR_CANCIONES INTO @CANCION
					WHILE (@@FETCH_STATUS = 0)
					BEGIN			 
						PRINT '						'+@CANCION
					FETCH NEXT FROM CURSOR_CANCIONES INTO @CANCION
					END
				CLOSE CURSOR_CANCIONES
				DEALLOCATE CURSOR_CANCIONES		
				FETCH NEXT FROM CURSOR_DISCOS INTO @titulo
			END
		CLOSE CURSOR_DISCOS
		DEALLOCATE CURSOR_DISCOS
		FETCH NEXT FROM CURSOR_GRUPO INTO @NOMBRE,@GrupoID
	END
CLOSE CURSOR_GRUPO
DEALLOCATE CURSOR_GRUPO 
