CREATE TRIGGER NO_BORRAR ON artistas
FOR DELETE
AS 
BEGIN
	DECLARE @VAR1 INT = (SELECT Artista_id FROM deleted)
	IF (@VAR1=100)
	BEGIN
		ROLLBACK
		print 'EL ID 100 NO SE PUEDE BORRAR'
	END
END